name = "med-portal"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

name = "covidaccountability"            # keep your current name
pages_build_output_dir = "public"       # keep whatever you already have
compatibility_date = "2025-01-01"       # keep your current date

# (optional) regular vars can live here; secrets like TURNSTILE_SECRET should stay in the dashboard, which you already have.

[[d1_databases]]
binding = "DB"                          # <-- must be exactly DB to match the code
database_name = "medportal_db"
database_id   = "84a3b4f0-70fe-4d09-8006-c35576e4e109"
