name = "covidaccountability"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"                    # must be exactly DB to match code
database_name = "medportal_db"    # <-- YOUR D1 database name
database_id   = "84a3b4f0-70fe-4d09-8006-c35576e4e109"  # <-- YOUR D1 database id
