# wrangler.toml — Cloudflare Pages + D1 (Sprint A)

name = "covidaccountability"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

# D1 binding (name must match the DB you use in commands)
[[d1_databases]]
binding        = "DB"                 # used by Functions as env.DB
database_name  = "medportal_db"
database_id    = "84a3b4f0-70fe-4d09-8006-c35576e4e109"
migrations_dir = "db/migrations"      # <-- must be inside this block

# Existing KV binding (unchanged)
[[kv_namespaces]]
binding = "OPEN_BOARD_KV"
id = "7c170dc902a84accbea22533d4fab918"
preview_id = "588aee7fd81a492ab92fc0f12f6791b6"
