-- Generated by apply-states.mjs
PRAGMA foreign_keys = ON;
INSERT INTO states (code,name,link,unavailable)
VALUES ('CA','California','https://www.mbc.ca.gov/Consumers/file-a-complaint/',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
INSERT INTO states (code,name,link,unavailable)
VALUES ('IN','Indiana','https://www.mbc.ca.gov/Consumers/File-a-Complaint/complaint-process.aspx',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
INSERT INTO states (code,name,link,unavailable)
VALUES ('ME','Maine','http://www.maine.gov/md/complaint',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
INSERT INTO states (code,name,link,unavailable)
VALUES ('OR','Oregon','https://www.oregon.gov/omb/investigations/pages/how-to-file-a-complaint.aspx',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
INSERT INTO states (code,name,link,unavailable)
VALUES ('PA','Pennsylvania','https://www.phila.gov/services/mental-physical-health/report-a-health-or-safety-concern/file-a-complaint-about-a-medical-provider/',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
INSERT INTO states (code,name,link,unavailable)
VALUES ('WY','Wyoming','https://wyomedboard.wyo.gov/consumers/file-a-complaint',0)
ON CONFLICT(code) DO UPDATE SET name=excluded.name, link=excluded.link, unavailable=0;
