# .github/workflows/audit-all.yml — DISABLED
name: DISABLED - Link audit (refs + states)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This legacy workflow is intentionally disabled. Use 'State Links Audit' and refs-only audits instead."
