name: Auto-approve references (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (if lockfile exists)
        run: |
          if [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ]; then
            npm ci || npm install
          fi

      - name: Run auto-approver
        run: node scripts/auto-approve-refs.mjs

      - name: Update audit report (optional)
        run: npm run audit:refs || true

      - name: Commit & push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/about.html db/ref-audit.csv
            git commit -m "chore(refs): auto-approve trusted references"
            git push
          else
            echo "No changes to commit."
          fi
