name: D1 sanity

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install wrangler
        run: npm i -g wrangler@^4.37.1
      - name: Counts
        run: |
          npx wrangler d1 execute medportal_db --remote --json --command "SELECT COUNT(*) AS c FROM states;"
          npx wrangler d1 execute medportal_db --remote --json --command "SELECT COUNT(*) AS c FROM boards;"
      - name: Peek states
        run: npx wrangler d1 execute medportal_db --remote --json --command "SELECT code,name FROM states ORDER BY code LIMIT 5;"
      - name: Peek boards
        run: npx wrangler d1 execute medportal_db --remote --json --command "SELECT state_code,board,primary_flag FROM boards ORDER BY state_code,primary_flag DESC,board LIMIT 10;"
