name: Link Health 2.0

on:
  workflow_dispatch: {}
  schedule:
    - cron: "21 5 * * *" # daily @ 05:21 UTC
  push:
    paths:
      - "public/assets/state-links.json"
      - "public/assets/references.json"
      - ".github/workflows/link-health.yml"
      - ".lychee.toml"
      - ".lycheeignore"
      - "scripts/verify-state-links.mjs"
      - "public/**/*.html"

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- A) General link audit (Lychee) ----------
      - name: Run lychee (external link audit)
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          # Scan the whole 'public' dir (HTML + JSON). Lychee reads our TOML/ignore automatically.
          args: >
            --config .lychee.toml
            --verbose
            public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save lychee results (stdout) into a file for the combined report
      - name: Save lychee output
        run: |
          mkdir -p reports
          echo "### Lychee Summary" > reports/link-health.md
          echo "" >> reports/link-health.md
          echo '```' >> reports/link-health.md
          echo "${{ steps.lychee.outputs.output }}" >> reports/link-health.md
          echo '```' >> reports/link-health.md

      # ---------- B) State landing host verifier ----------
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify state links (follow redirects, validate final host)
        id: states
        run: |
          node scripts/verify-state-links.mjs >> reports/link-health.md

      # ---------- Upload combined report ----------
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: link-health-report
          path: reports/link-health.md
          retention-days: 14

      # ---------- Decide overall job result ----------
      - name: Fail if there were hard errors
        run: |
          echo "Lychee exit code: ${{ steps.lychee.outcome }}"
          echo "States verifier exit code: ${{ steps.states.outcome }}"
        if: failure()
