name: Link Health 2.0

on:
  workflow_dispatch: {}
  schedule:
    - cron: "21 5 * * *"   # daily 05:21 UTC
  push:
    paths:
      - "public/assets/state-links.json"
      - "public/assets/states.json"
      - "public/**/*.html"
      - "scripts/verify-state-links.mjs"
      - ".github/workflows/link-health.yml"
      - ".lychee.toml"
      - ".lycheeignore"

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    env:
      STATE_ENFORCE: "false"  # flip to "true" later to fail on FAIL rows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee (external link audit)
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        continue-on-error: true
        with:
          args: >
            --config .lychee.toml
            --verbose
            public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build combined report (header + lychee stdout)
        run: |
          mkdir -p reports
          echo "### Lychee Summary" > reports/link-health.md
          echo "" >> reports/link-health.md
          echo '```' >> reports/link-health.md
          echo "${{ steps.lychee.outputs.output }}" >> reports/link-health.md
          echo '```' >> reports/link-health.md
          echo "" >> reports/link-health.md

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify state links (follow redirects, validate final host)
        id: states
        continue-on-error: true
        run: |
          node scripts/verify-state-links.mjs >> reports/link-health.md

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-health-report
          path: reports/link-health.md
          retention-days: 14

      - name: Fail if there were hard errors
        if: always()
        run: |
          echo "Lychee step:  ${{ steps.lychee.outcome }}"
          echo "States step:  ${{ steps.states.outcome }}"
          # Only hard-fail for lychee; state verifier is report-only unless STATE_ENFORCE=true
          if [ "${{ steps.lychee.outcome }}" != "success" ]; then
            echo "Lychee found a hard error (config/network); failing."
            exit 1
          fi
          if [ "${{ env.STATE_ENFORCE }}" = "true" ] && [ "${{ steps.states.outcome }}" != "success" ]; then
            echo "State verifier in ENFORCE mode; failing due to state errors."
            exit 1
          fi
