name: Auto-approve references (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write    # allow commit back to main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node --version
      - name: Run strict auto-approver
        run: node scripts/auto-approve-refs.mjs
      - name: Audit (post)
        run: npm run audit:refs || true
      - name: Commit changes (if any)
        run: |
          git add public/about.html db/ref-audit.csv db/ref-candidates.csv
          git diff --cached --quiet || git commit -m "chore(refs): auto-approve + audit"
          git push
      - name: Upload audit
        uses: actions/upload-artifact@v4
        with:
          name: ref-audit
          path: db/ref-audit.csv

