name: release-tag

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # allow pushing tags and creating releases

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build tag name
        id: build_tag
        run: |
          TS=$(date -u +"%Y.%m.%d-%H%M")
          echo "tag=v${TS}" >> "$GITHUB_OUTPUT"

      - name: Configure git identity
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Create annotated tag
        run: |
          TAG="${{ steps.build_tag.outputs.tag }}"
          git tag -a "$TAG" -m "Automated release tag"
          git push origin "$TAG"

      - name: Create GitHub Release (optional)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
