name: D1 → state-links.json (export)

on:
  workflow_dispatch:
  # Optional schedule when you want it to auto-refresh:
  # schedule:
  #   - cron: "12 9 * * *"   # daily @ 09:12 UTC

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm i -g wrangler@4.37.1
      - run: sudo apt-get update && sudo apt-get install -y jq

      # DEBUG – keep for future triage, but disabled by default
      # - name: DEBUG – whoami & d1 list
      #   run: |
      #     wrangler whoami
      #     wrangler d1 list --json | jq -r '.[] | "\(.name)  \(.uuid)"'

      - name: Apply migrations (D1)
        run: wrangler d1 migrations apply medportal_db --remote

      - name: Seed boards from JSON
        run: node scripts/seed-boards-from-json.mjs

      - name: Export D1 → public/assets/state-links.json
        run: node scripts/export-state-links-from-d1.mjs

      - name: Validate exported JSON
        run: node scripts/validate-state-links.mjs

      - name: Sanity guard (min states)
        run: |
          COUNT=$(jq 'length' public/assets/state-links.json)
          echo "states in export: $COUNT"
          if [ "$COUNT" -lt 50 ]; then
            echo "Refusing to commit: export has fewer than 50 states."
            exit 1
          fi

      - name: Commit exported JSON (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add public/assets/state-links.json
            git commit -m "chore(export): D1 → state-links.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
