name: state-links delta comment

on:
  pull_request:
    paths:
      - 'public/assets/state-links.json'

jobs:
  delta:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute host delta
        id: diff
        run: |
          set -euo pipefail
          FILE="public/assets/state-links.json"
          BASE="${{ github.event.pull_request.base.sha }}"
          git show "$BASE:$FILE" > /tmp/base.json || echo "[]" > /tmp/base.json
          jq -r '.[].links[].url' /tmp/base.json | sed 's#^https\?://##' | cut -d/ -f1 | sort -u > /tmp/base.hosts || true
          jq -r '.[].links[].url' "$FILE" | sed 's#^https\?://##' | cut -d/ -f1 | sort -u > /tmp/head.hosts || true
          ADDED=$(comm -13 /tmp/base.hosts /tmp/head.hosts | sed 's/^/- added: /' || true)
          REMOVED=$(comm -23 /tmp/base.hosts /tmp/head.hosts | sed 's/^/- removed: /' || true)
          SUMMARY=""
          if [ -n "$ADDED" ]; then SUMMARY="$SUMMARY$ADDED"$'\n'; fi
          if [ -n "$REMOVED" ]; then SUMMARY="$SUMMARY$REMOVED"$'\n'; fi
          if [ -z "$SUMMARY" ]; then SUMMARY="No host changes (links updated or reordered)."; fi
          {
            echo "summary<<'EOF'"
            echo "$SUMMARY"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const body = [
              '### State Links Delta',
              '',
              'Hosts added/removed in `public/assets/state-links.json`:',
              '',
              process.env.SUMMARY
            ].join('\n');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          SUMMARY: ${{ steps.diff.outputs.summary }}
