name: Uptime & Smoke (daily)

on:
  schedule:
    - cron: "20 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for PR updates)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Probe pages
        id: probe
        run: |
          set -e
          BASE="${{ secrets.SITE_BASE_URL }}"
          if [ -z "$BASE" ]; then echo "SITE_BASE_URL missing"; exit 1; fi
          mkdir -p reports
          TS=$(date -u +%Y%m%dT%H%M%SZ)
          OUT="reports/uptime-$TS.json"
          urls=("$BASE/" "$BASE/about.html" "$BASE/references.html" "$BASE/complaint-portal.html")
          echo "[" > "$OUT"
          first=1
          for u in "${urls[@]}"; do
            start=$(date +%s%3N)
            code=$(curl -s -o /dev/null -w "%{http_code}" "$u")
            dur=$(( $(date +%s%3N) - start ))
            # Minimal content sanity: ensure document looks like HTML
            head=$(curl -s --max-time 10 "$u" | head -c 200 | tr -d '\n' | sed 's/"/\\"/g')
            [ $first -eq 0 ] && echo "," >> "$OUT"
            first=0
            echo "{\"url\":\"$u\",\"status\":$code,\"ms\":$dur,\"snippet\":\"$head\"}" >> "$OUT"
          done
          echo "]" >> "$OUT"
          echo "OUT=$OUT" >> $GITHUB_OUTPUT

      - name: Upload artifact (30 days)
        uses: actions/upload-artifact@v4
        with:
          name: uptime-smoke
          path: ${{ steps.probe.outputs.OUT }}
          retention-days: 30

      - name: Write latest roll-up + commit (warn-only)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ops): update uptime roll-up"
          file_pattern: "reports/uptime-*.json"
          # Also keep a LATEST pointer for convenience
      - name: Create LATEST pointer
        run: |
          cp "${{ steps.probe.outputs.OUT }}" reports/LATEST.uptime.json
      - name: Commit LATEST pointer
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ops): refresh LATEST.uptime.json"
          file_pattern: "reports/LATEST.uptime.json"

      # Keep CI green no matter what
      - name: Always succeed
        if: always()
        run: echo "warn-only"
