name: Build VAERS summary JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 5 * *" # monthly on the 5th at 06:00 UTC (adjust as you like)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dev deps
        run: npm install --no-save adm-zip csv-parse

      - name: Build vaers-summary.json
        run: node scripts/vaers-build.mjs

      - name: Commit updated data
        uses: EndBug/add-and-commit@v9
        with:
          add: "public/data/vaers-summary.json"
          message: "chore(data): update VAERS summary JSON [skip ci]"
